USE empresa;

SELECT A.FECHA, SUM(B.CANTIDAD*B.PRECIO) AS FACTURACION
FROM facturas A
INNER JOIN
items B
ON A.NUMERO = B.NUMERO
WHERE A.FECHA = '20230513'
GROUP BY A.FECHA;

CALL sp_venta('20230515', 40, 50);