USE empresa;

CREATE TABLE clientes(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR (100) NULL,
DIRECCION VARCHAR (150) NULL,
BARRIO VARCHAR (50) NULL,
CIUDAD VARCHAR (50) NULL,
ESTADO VARCHAR (10) NULL,
CP VARCHAR (10) NULL,
FECHA_NACIMIENTO DATE NULL,
EDAD SMALLINT NULL,
SEXO VARCHAR (1) NULL, 
LIMITE_CREDITO FLOAT NULL,
VOLUMEN_COMPRA FLOAT NULL,
PRIMERA_COMPRA BIT NULL,
PRIMARY KEY (DNI)
);

SELECT * FROM clientes;
SELECT * FROM vendedores;

CREATE TABLE facturas(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT NULL,
PRIMARY KEY (NUMERO),
FOREIGN KEY (DNI) REFERENCES clientes(DNI),
FOREIGN KEY (MATRICULA) REFERENCES vendedores(MATRICULA)
);

SELECT * FROM facturas;

CREATE TABLE items(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT NULL,
PRECIO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO),
FOREIGN KEY (NUMERO) REFERENCES facturas(NUMERO),
FOREIGN KEY (CODIGO) REFERENCES productos(CODIGO)
);

SELECT * FROM items;

