USE empresa;

SELECT f_cliente_aleatorio() AS DNI_CLIENTE,
f_producto_aleatorio() AS PRODUCTO,
f_vendedor_aleatorio() AS VENDEDOR;

SELECT MAX(NUMERO) AS MONTO_MAXIMO FROM facturas;

CALL sp_venta('20230513', 10, 100);

SELECT MAX(NUMERO) FROM facturas;

SELECT COUNT(*) FROM facturas;

SELECT NUMERO FROM facturas ORDER BY NUMERO DESC LIMIT 88000;

CREATE TABLE facturas(
NUMERO INT NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT NULL,
PRIMARY KEY (NUMERO),
FOREIGN KEY (DNI) REFERENCES clientes(DNI),
FOREIGN KEY (MATRICULA) REFERENCES vendedores(MATRICULA)
);

SELECT * FROM facturas;

CREATE TABLE items(
NUMERO INT NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT NULL,
PRECIO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO),
FOREIGN KEY (NUMERO) REFERENCES facturas(NUMERO),
FOREIGN KEY (CODIGO) REFERENCES productos(CODIGO)
);

SELECT * FROM items;

INSERT INTO items 
SELECT NUMERO, CODIGO_DEL_PRODUCTO AS CODIGO, CANTIDAD, PRECIO
FROM jugos_ventas.items_facturas;

INSERT INTO facturas 
SELECT NUMERO, FECHA_VENTA AS FECHA, DNI, MATRICULA, IMPUESTO
FROM jugos_ventas.facturas;